pipeline:

#  security-check:
#    image: dan78uk/node-build-docker:v1
#    commands:
#      - git log -1 -p | scanrepo
#      - nsp check
#
#  unit-test:
#    image: node:6.11
#    commands:
#      - npm install --quiet
#      - npm test

# TODO: fix versions of images

  test-deployment:
    image: quay.io/ukhomeofficedigital/kd:latest
    secrets: [kube_token]
    commands:
      - echo "deploying to namespace...."

  # TODO: run performance test against deployed api
  performance-test:
    image: blazemeter/taurus:latest
    commands:
      - bzt -o settings.artifacts-dir=taurus_artifacts performance.yml

  save-report:
    image: quay.io/ukhomeofficedigital/awscli:latest
    secrets:
      # TODO: tidy secret keys - don't need to be renamed?
      - source: s3_access_key
        target: access_key
      - source: s3_secret_key
        target: secret_key
      - source: kms_key
        target: kms_key_id
    environment:
      - AWS_DEFAULT_REGION=eu-west-2
    commands:
      - export AWS_ACCESS_KEY_ID=$ACCESS_KEY
      - export AWS_SECRET_ACCESS_KEY=$SECRET_KEY
      - aws s3 cp taurus_artifacts/ s3://taurus-project-x/taurus_artifacts/ --sse aws:kms --sse-kms-key-id $KMS_KEY_ID