pipeline:

#  security-check:
#    image: dan78uk/node-build-docker:v1
#    commands:
#      - git log -1 -p | scanrepo
#      - nsp check
#
#  unit-test:
#    image: node:6.11
#    commands:
#      - npm install --quiet
#      - npm test

#  test-deployment:
#    # step w/ kube_token & kube_server secrets
#    secrets:
#      - source: kube_token
#        target: aws_access_key_id
#      - source: kube_server
#        target: aws_secret_access_key

  performance-test:
    image: blazemeter/taurus:latest
    commands:
      - bzt -o settings.artifacts-dir=taurus_artifacts performance.yml

  save-report:
    image: quay.io/ukhomeofficedigital/awscli:latest
    secrets:
      - source: s3_access_key
        target: access_key
      - source: s3_secret_key
        target: secret_key
      - source: kms_key
        target: kms_key_id
    environment:
      - AWS_ACCESS_KEY_ID=$ACCESS_KEY
      - AWS_SECRET_ACCESS_KEY=$SECRET_KEY
      - AWS_DEFAULT_REGION=eu-west-2
      - KMS_KEY_ID=$KMS_KEY_ID
    commands:
      - aws s3 cp README.md s3://taurus-project-x/README.md --sse aws:kms --sse-kms-key-id $KMS_KEY_ID