pipeline:

  security-check:
    image: dan78uk/node-build-docker:v1
    commands:
      - git log -1 -p | scanrepo
      - nsp check

  build:
    image: node:6.11
    commands:
      - npm install --quiet
      - npm run build
      - npm run test
      - cp config.production.json dist/config.json

  publish-image:
    image: docker:1.11
    secrets:
      - DOCKER_REPO_PASSWORD
    environment:
      - DOCKER_HOST=tcp://172.17.0.1:2375
      - REPOSITORY_HOST=quay.io
      - REPOSITORY_USER=ukhomeofficedigital+taurus_robot
      - IMAGE_DIR=/ukhomeofficedigital/
      - IMAGE_NAME=taurus-project-x
    commands:
      - FULL_IMAGE_PATH=$REPOSITORY_HOST$IMAGE_DIR$IMAGE_NAME
      - PACKAGE_VERSION=$(grep version package.json | sed 's/[^0-9\.]//g' | tr -d '[[:space:]]')
      - SHORT_HASH=$(echo $DRONE_COMMIT | cut -c1-7)
      - TAG=$PACKAGE_VERSION"_"$SHORT_HASH"_"$DRONE_BUILD_NUMBER
      - docker build -t $FULL_IMAGE_PATH:$TAG .
      - docker login -u="$${REPOSITORY_USER}" -p="$${DOCKER_REPO_PASSWORD}" "$${REPOSITORY_HOST}"
      - docker push $FULL_IMAGE_PATH:$TAG

  test-deployment:
    image: quay.io/ukhomeofficedigital/kd:v0.7.0
    secrets: [KUBE_SERVER, KUBE_TOKEN]
    commands:
      - apk update
      - apk add curl
      - bash scripts/deploy.sh
      - sleep 30

  performance-test:
    image: quay.io/ukhomeofficedigital/taurus-bzt:0.0.0
    commands:
      - bzt -o settings.artifacts-dir=taurus_artifacts performance.yml
      - bash ~/.bzt/jmeter-taurus/3.3/bin/jmeter -g taurus_artifacts/kpi.jtl -o taurus_artifacts/dashboard/

  save-report:
    image: quay.io/ukhomeofficedigital/awscli:latest
    secrets: [s3_access_key, s3_secret_key, kms_key]
    environment:
      - AWS_DEFAULT_REGION=eu-west-2
    commands:
      - export AWS_ACCESS_KEY_ID=$S3_ACCESS_KEY
      - export AWS_SECRET_ACCESS_KEY=$S3_SECRET_KEY
      - SHORT_HASH=$(echo $DRONE_COMMIT | cut -c1-7)
      - aws s3 cp --recursive ./taurus_artifacts/dashboard/ s3://taurus-project-x/$IMAGE_NAME/$SHORT_HASH --sse aws:kms --sse-kms-key-id $KMS_KEY