pipeline:

#  security-check:
#    image: dan78uk/node-build-docker:v1
#    commands:
#      - git log -1 -p | scanrepo
#      - nsp check
#
#  unit-test:
#    image: node:6.11
#    commands:
#      - npm install --quiet
#      - npm test

#  test-deployment:
#    # step w/ kube_token & kube_server secrets
#    secrets:
#      - source: kube_token
#        target: aws_access_key_id
#      - source: kube_server
#        target: aws_secret_access_key

  performance-test:
    image: blazemeter/taurus:latest
    commands:
      - mkdir taurus_artifacts
      - bzt -o settings.artifacts-dir=taurus_artifacts performance.yml

#  save-report:
#    image: plugins/s3
#    secrets:
#      - source: s3_access_key
#        target: access_key
#      - source: s3_secret_key
#        target: secret_key
#    bucket: taurus-project-x
#    source: taurus_artifacts/*
#    target: /
#    access_key:

  save-report:
    image: quay.io/ukhomeofficedigital/s3secrets:v1.0.3
    secrets:
      - source: s3_access_key
        target: access_key
      - source: s3_secret_key
        target: secret_key
    commands:
      - bin/s3secrets --region eu-west-2 --access-key $ACCESS_KEY --secret-key $SECRET_KEY list --bucket taurus-project-x

