pipeline:

#  security-check:
#    image: dan78uk/node-build-docker:v1
#    commands:
#      - git log -1 -p | scanrepo
#      - nsp check
#
#  unit-test:
#    image: node:6.11
#    commands:
#      - npm install --quiet
#      - npm test

  test-deployment:
    image: quay.io/ukhomeofficedigital/kd:v0.7.0
    secrets: [KUBE_SERVER, KUBE_TOKEN]
    commands:
      - echo "deploying to namespace...."
      - ./scripts/deploy.sh
      - sleep 30

  # TODO: run performance test against deployed api
  performance-test:
    image: blazemeter/taurus:1.10.4
    commands:
      - bzt -o settings.artifacts-dir=taurus_artifacts performance.yml

  save-report:
    image: quay.io/ukhomeofficedigital/awscli:latest
    secrets: [s3_access_key, s3_secret_key, kms_key]
    environment:
      - AWS_DEFAULT_REGION=eu-west-2
    commands:
      - export AWS_ACCESS_KEY_ID=$S3_ACCESS_KEY
      - export AWS_SECRET_ACCESS_KEY=$S3_SECRET_KEY
      - aws s3 cp taurus_artifacts/ s3://taurus-project-x/taurus_artifacts/ --sse aws:kms --sse-kms-key-id $KMS_KEY