pipeline:

  security-check:
    image: dan78uk/node-build-docker:v1
    commands:
      - git log -1 -p | scanrepo
      - nsp check

  unit-test:
    image: node:6.11
    commands:
      - npm install --quiet
      - npm test

#  test-deployment:
#    # step w/ kube_token & kube_server secrets
#    secrets:
#      - source: kube_token
#        target: aws_access_key_id
#      - source: kube_server
#        target: aws_secret_access_key

  performance-test:
    image: blazemeter/taurus:latest
    commands:
      - mkdir taurus_artifacts
      - bzt -o settings.artifacts-dir=taurus_artifacts performance.yml

  debug:
    image: node:6.11
    secrets:
      - source: s3_access_key
        target: access_key
      - source: s3_access_key
        target: secret_key
    commands:
      - echo ====
      - echo $s3_access_key
      - echo ====
      - echo access_key

  save-report:
    image: plugins/s3
#    secrets:
#      - source: s3_access_key
#        target: access_key
#      - source: s3_secret_key
#        target: secret_key
    bucket: taurus-project-x
    source: taurus_artifacts/*
    target: /

#  save-report:
#    image: quay.io/ukhomeofficedigital/drone-s3cache:latest
#    drone_s3_cache_folders: "taurus_artifacts"
#    drone_s3_cache_mode: "push"