apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: taurus-project-x-network-policy
spec:
  podSelector:
    matchLabels:
      app: taurus-project-x
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: ingress-internal
    - podSelector:
        matchLabels:
          name: ingress
    ports:
    - protocol: TCP
      port: 1337